### ISSUE TITLE
Related project: Tracktable

### ISSUE THREAD

**Issue by anitagraser** [adonmo/meos#32]
Just wanted to share with you a similar project with C++ core data structures and algorithms combined with Python API: https://github.com/sandialabs/tracktable

**Comment by chaitan94** [comment]
That's a really interesting project. Thanks for sharing, I will be exploring it soon! :)

**Comment by chaitan94** [comment]
Closing this issue. If anyone else is looking for similar/related projects, check out: https://github.com/anitagraser/movement-analysis-tools
